:ets.new(:mt, [:named_table])
:ets.insert_new(:mt, {:key1, ["my", "value"]})
val1 = :ets.lookup(:mt, :key1)
not_found_val1 = :ets.lookup(:mt, :not_a_key)
:ets.insert_new(:mt, {"key2", "my other value"})
val2 = :ets.lookup(:mt, "key2")
not_found_val2 = :ets.lookup(:mt, :key2)
:ets.delete(:mt, "key2")
not_found_val2 = :ets.lookup(:mt, "key2")
:ets.delete(:mt)
